version: "3"

services:
  hive-server:
    image: lenchv/hive:2.3.6
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: /opt/apache-hive-2.3.6-bin/bin/hiveserver2
    hostname: volodymyr.local
    volumes:
      - ./confs/hive-site.xml:/opt/apache-hive-2.3.6-bin/conf/hive-site.xml
      - ./ssl/:/opt/ssl/
  hive-metastore:
    image: lenchv/hive:2.3.6
    hostname: volodymyr.local
    ports:
      - "9083:9083"
    volumes:
      - ./confs/hive-site.xml:/opt/apache-hive-2.3.6-bin/conf/hive-site.xml
      - ./ssl/:/opt/ssl/
    command: /opt/apache-hive-2.3.6-bin/bin/hive --service metastore
  openldap:
    image: osixia/openldap:1.2.4
    hostname: hive.driver
    environment:
      LDAP_ORGANISATION: lenchv
      LDAP_DOMAIN: hive.driver
      LDAP_ADMIN_PASSWORD: "123456"
      LDAP_LOG_LEVEL: "256"
      LDAP_TLS: "false"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"